PMM-7344 update to 0.8.0
percona/postgres_exporter pull request #30
Opened 2021-03-02 10:27 UTC by askomorokhov

https://jira.percona.com/browse/PMM-7344

2021-03-02 10:27 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/postgres_exporter?pullRequest=30) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/postgres_exporter?pullRequest=30) before we can accept your contribution.<br/>**1** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: askomorokhov<br/>:x: AlexisSellier<br/>:x: d-ulyanov<br/>:x: dmolik<br/>:x: wlfshmn<br/>:x: wosc<br/>:x: michaelkaye<br/>:x: focabr<br/>:x: nieltg<br/>:x: wrouesnel<br/>:x: costela<br/>:x: headcr4sh<br/>:x: vovka667<br/>:x: russss<br/>:x: SuperQ<br/>:x: sfalkon<br/>:x: Jaroslav Musil<br/><hr/>**Jaroslav Musil** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/postgres_exporter?pullRequest=30) it.</sub>

2021-03-02 20:36 UTC, percona-csalguero requested changes

2021-03-02 20:36 UTC, percona-csalguero commented on README.md
> +  Whether to discover the databases on a server dynamically.
Wheter? If we use wether the phrase would be `wether blah blah blah or not`.
Can we change it to something like `enable discovering databases automatically`?

2021-03-02 20:36 UTC, percona-csalguero commented on README.md
> +  Whether to discover the databases on a server dynamically. Value can be `true` or `false`. Defauls is `false`.
Wether again.

2021-03-04 10:22 UTC, JiriCtvrtka approved these changes

2021-03-04 11:39 UTC, percona-csalguero approved these changes

2021-03-11 14:05 UTC, merged